name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1

      - name: Install dependencies
        working-directory: mvp-building
        run: pnpm install --frozen-lockfile

      - name: Build each deck with absolute base and out
        working-directory: mvp-building
        run: |
          pnpm exec slidev build 01_mvp_planning.md \
            --base /${{ github.event.repository.name }}/01_mvp_planning/ \
            --out dist/01_mvp_planning
          pnpm exec slidev build 02_mvp_building.md \
            --base /${{ github.event.repository.name }}/02_mvp_building/ \
            --out dist/02_mvp_building

      # No root index.html needed; each deck is accessed directly

      - name: Create root 404.html for GH Pages SPA fallback
        working-directory: mvp-building/dist
        run: |
          cat > 404.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Redirecting…</title>
          </head>
          <body>
            <script>
            (function () {
              var repo = '/${{ github.event.repository.name }}/';
              var path = location.pathname;
              if (!path.startsWith(repo)) { location.replace(repo); return; }
              var rest = path.slice(repo.length);
              var deck = rest.split('/')[0];
              if (deck === '01_mvp_planning' || deck === '02_mvp_building') {
                location.replace(repo + deck + '/');
              } else {
                location.replace(repo);
              }
            })();
            </script>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: mvp-building/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


